---
handlers:
  - secure: always
    static_dir: build/static
    url: /static
    http_headers:
      Access-Control-Allow-Origin: https://nwitter-backend.du.r.appspot.com/

  - secure: always
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$
    url: /(.*\.(json|ico|js))$
    http_headers:
      Access-Control-Allow-Origin: https://nwitter-backend.du.r.appspot.com/

  - secure: always
    static_files: build/index.html
    upload: build/index.html
    url: .*
    http_headers:
      Access-Control-Allow-Origin: https://nwitter-backend.du.r.appspot.com/

manual_scaling:
  instances: 1
runtime: nodejs16
